include:
  remote: 'https://github.com/git-developer/solarview-base/raw/v1.12.1/.gitlab-ci.yml'

variables:
  DOCKERFILE_URL: 'https://github.com/git-developer/solarview-base/raw/v1.12.1/Dockerfile'
  BUILD_ARGS: 'APP_NAME=smapbt-fb APP_PACKAGES=libbluetooth3,bluez,sudo'
  IMAGE_TITLE: 'SolarView SMA Bluetooth-Proxy'
  UPDATE_CHECK_URLS: 'http://www.solarview.info/downloads/smapbt-fb.zip'
